export const plans = {
  yearly: [
    {
      imageGenerations: 600,
      chatGenerations: 600,
      commercialUse: true,
      unlockPro: false,
      plan: "basic",
      price: 4.99,
      period: "year",
      name: "BASIC_YEARLY",
      priceTag: "price_1MfpM1HrZAHisucb3J4nzdYn",
    },
    {
      imageGenerations: 1200,
      chatGenerations: 1440,
      commercialUse: true,
      unlockPro: true,
      plan: "pro",
      price: 7.99,
      period: "year",
      name: "PRO_YEARLY",
      priceTag: "price_1MfpM1HrZAHisucb3J4nzdYn",
    },
    {
      imageGenerations: 4800,
      chatGenerations: 6000,
      commercialUse: true,
      unlockPro: true,
      plan: "proPlus",
      price: 24.99,
      period: "year",
      name: "PRO_PLUS_YEARLY",
      priceTag: "price_1MfpM1HrZAHisucb3J4nzdYn",
    },
  ],

  monthly: [
    {
      imageGenerations: 50,
      chatGenerations: 50,
      commercialUse: true,
      unlockPro: false,
      plan: "basic",
      price: 5.99,
      period: "month",
      name: "BASIC_MONTHLY",
      priceTag: "price_1MfpM1HrZAHisucb3J4nzdYn",
    },
    {
      imageGenerations: 100,
      chatGenerations: 120,
      commercialUse: true,
      unlockPro: true,
      plan: "pro",
      price: 8.99,
      period: "month",
      name: "PRO_MONTHLY",
      priceTag: "price_1MfpM1HrZAHisucb3J4nzdYn",
    },
    {
      imageGenerations: 400,
      chatGenerations: 500,
      commercialUse: true,
      unlockPro: true,
      plan: "proPlus",
      price: 29.99,
      period: "month",
      name: "PRO_PLUS_MONTHLY",
      priceTag: "price_1MfpM1HrZAHisucb3J4nzdYn",
    },
  ],
};
